version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "e_commerce_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./data:/var/lib/mysql

